### GET request to example server
GET {{host}}/aircrafts

###

### Create Aircraft
POST {{host}}/aircrafts
Content-Type: application/json

{
  "display_name": "Husky A-1A",
  "registration": "HB-KIP"
}
###
